FROM ruby:3.3-slim

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  git \
  libyaml-dev \
  pkg-config \
  curl \
  libjemalloc2 \
  libvips \
  sqlite3 \
  vim \
  && apt-get upgrade -y \
  && rm -rf /var/lib/apt/lists /var/cache/apt/archives
